### ISSUE TITLE
-fsanitze=adress

### ISSUE THREAD

**Issue by otiza** [Alexdelia/42-exam#1]
Have you tried to compile it with the -fsanitize=address flag?

**Comment by Alexdelia** [comment]
I've use valgrind to test the leaks.

-fsanitize=address abort into ft_strlen with a read of str[i] = '\0'.
there is no need to fix that.
you could make sure that (i < BUFFER_SIZE) but it will abort again the next time you test str[i] and it's equal to '\0'

it will be easier to talk through discord or other media than by error. Here is my discord: Alexdelia#0001

**Comment by otiza** [comment]
hey i didn't receive your discord this is mine amaaiza#5254

**Comment by otiza** [comment]
and take a look at what i did here:

char	*ft_strdup(char *s)
{
	int		n;
	char	*iter;
	char	*str;

	n = ft_strlen(s);
	str = (char*)malloc(sizeof(char) * (n + 1));
	iter = str;
	while (*s)
		*iter++ = *s++;
	*iter = 0;
	return (str);
}

char	*ft_strjoin(char *s1, char *s2)
{
	char	*str;
	char	*iter;

	str = (char*)malloc(sizeof(char) * (ft_strlen(s1) + ft_strlen(s2) + 1));
	iter = str;
	while (*s1)
		*iter++ = *s1++;
	while (*s2)
		*iter++ = *s2++;
	*iter = 0;
	return (str);
}

char	*before_end_l(char *str)
{
	int		len;
	char	*line;
	char	*iter;

	if ((len = ft_is_line(str)) < 0)
		len = ft_strlen(str);
	line = (char*)malloc(sizeof(char) * (len + 2));
	iter = line;
	while (*str && *str != '\n')
	{	
		*iter++ = *str++;

	}
	*iter++ = *str;
	*iter = 0;
	return (line);
}

char	*after_end_l(char *str)
{
	int		indice;
	char	*line;
	char	*iter;


	if ((indice = ft_is_line(str)) < 0)
		return (NULL);
	line = (char*)malloc(sizeof(char) * (ft_strlen(str) - indice + 2));
	iter = line;
	str += indice + 1;
	while (*str)
		*iter++ = *str++;
	*iter = 0;
	return (line);
}

char	*ft_get_line(char **line, char **rest)
{
	char	*str;

	str = before_end_l(*line);
	*rest = after_end_l(*line);
	free(*line);
	return (str);
}

char	*get_next_line(int fd)
{
	char		*line;
	static char	*rest = NULL;
	char		*tmp;
	char		*buffer;
	int			n;

	if (!rest)
		rest = ft_strdup("");
	line = ft_strdup(rest);
	free(rest);
	rest = NULL;
	while(42)
	{
		if(ft_is_line(line) >= 0)
			return (ft_get_line(&line, &rest));
		buffer = (char*)malloc(sizeof(char) * (BUFFER_SIZE + 1));
		n = read(fd, buffer, BUFFER_SIZE);
		buffer[n] = 0;
		tmp = ft_strjoin(line, buffer);
		free(line);
		free(buffer);
		line = tmp;
		if (!n)
		{
			if (*line)
				return(line);
			else
			{
				free(line);
				return (NULL);
			}
		}
	}
}

**Comment by Alexdelia** [comment]
I've sent you a discord friend request.

you now malloc your static ?

btw, I've just passed the exam this morning, didn't work out, don't know yet, but it might be because of something called "sequential read"
